#spring.flyway.enabled: false

spring:
  datasource:
    url: jdbc:postgresql://192.168.1.64:5432/transactions
    username: transactions
    password: postgres
  flyway:
    baseline-on-migrate: true