version: '3'

services:
  postgres-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - 5432:5432
    # volumes:
    #   - c:/development/database/postgres/data:/var/lib/postgresql/data
