CREATE TABLE IF NOT EXISTS ACCOUNTS (
    ID UUID NOT NULL PRIMARY KEY ,
    DOCUMENT_NUMBER VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS OPERATIONS_TYPES (
    ID UUID NOT NULL PRIMARY KEY,
    DESCRIPTION VARCHAR(255) NOT NULL,
    OPERATION VARCHAR(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS TRANSACTIONS (
    ID UUID NOT NULL PRIMARY KEY,
    ACCOUNT_ID UUID NOT NULL,
    OPERATION_TYPE_ID UUID NOT NULL,
    AMOUNT NUMERIC NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE
);

ALTER TABLE TRANSACTIONS
    ADD CONSTRAINT FK_TRANSACTION_ACCOUNT
        FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS;

ALTER TABLE TRANSACTIONS
    ADD CONSTRAINT FK_TRANSACTION_OPERATION_TYPE
        FOREIGN KEY (OPERATION_TYPE_ID) REFERENCES OPERATIONS_TYPES;