CREATE TABLE IF NOT EXISTS ACCOUNTS
(
    ID              BIGSERIAL   NOT NULL PRIMARY KEY,
    DOCUMENT_NUMBER VARCHAR(11) NOT NULL
);

CREATE TABLE IF NOT EXISTS OPERATIONS_TYPES
(
    ID          BIGSERIAL    NOT NULL PRIMARY KEY,
    DESCRIPTION VARCHAR(255) NOT NULL,
    OPERATION   VARCHAR(10)  NOT NULL
);

CREATE TABLE IF NOT EXISTS TRANSACTIONS
(
    ID                BIGSERIAL NOT NULL PRIMARY KEY,
    ACCOUNT_ID        BIGINT    NOT NULL,
    OPERATION_TYPE_ID BIGINT    NOT NULL,
    AMOUNT            NUMERIC   NOT NULL,
    CREATED_AT        TIMESTAMP WITH TIME ZONE
);

ALTER TABLE TRANSACTIONS
    ADD CONSTRAINT FK_TRANSACTION_ACCOUNT
        FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS;

ALTER TABLE TRANSACTIONS
    ADD CONSTRAINT FK_TRANSACTION_OPERATION_TYPE
        FOREIGN KEY (OPERATION_TYPE_ID) REFERENCES OPERATIONS_TYPES;

INSERT INTO OPERATIONS_TYPES(description, operation)
VALUES ('COMPRA A VISTA', 'DEBIT'),
       ('COMPRA PARCELADA', 'DEBIT'),
       ('SAQUE', 'DEBIT'),
       ('PAGAMENTO', 'CREDIT');